*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:18:48 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:8888 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x2964d00
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x2964d00 pid: 3791 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3791)
spawned uWSGI worker 1 (pid: 3792, cores: 4)
spawned uWSGI worker 2 (pid: 3793, cores: 4)
DAMN ! worker 2 (pid: 3793) died :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 3808)
DAMN ! worker 1 (pid: 3792) died :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 3813)
DAMN ! worker 2 (pid: 3808) died :( trying respawn ...
Respawned uWSGI worker 2 (new pid: 3814)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/django/web/untitled
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3/bin/uwsgi
realpath() of uwsgi.ini failed: No such file or directory [core/utils.c line 3651]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:37:13 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:46:57 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:48:27 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:50:06 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 19:51:10 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (0.0.0.0:80).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 20:00:41 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to UNIX address /home/web/django/web/untitled/uwsgi.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x176f1d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x176f1d0 pid: 3993 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 3993)
spawned uWSGI worker 1 (pid: 3994, cores: 4)
spawned uWSGI worker 2 (pid: 3995, cores: 4)
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 20:04:48 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
bind(): Cannot assign requested address [core/socket.c line 769]
*** Starting uWSGI 2.0.17.1 (64bit) on [Mon Feb 18 20:06:08 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 127.0.0.1:8888 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x188c6d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x188c6d0 pid: 4028 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 4028)
spawned uWSGI worker 1 (pid: 4029, cores: 4)
spawned uWSGI worker 2 (pid: 4030, cores: 4)
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 1/1] 119.4.250.169 () {42 vars in 708 bytes} [Mon Feb 18 12:06:17 2019] GET / => generated 3023 bytes in 14165 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 1/2] 119.4.250.169 () {44 vars in 708 bytes} [Mon Feb 18 12:06:32 2019] GET /favicon.ico => generated 2134 bytes in 98 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /query
[pid: 4029|app: 0|req: 2/3] 123.150.182.175 () {48 vars in 989 bytes} [Mon Feb 18 12:08:30 2019] GET /query => generated 2116 bytes in 4 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 3/4] 119.4.250.168 () {38 vars in 680 bytes} [Mon Feb 18 12:08:30 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 4/5] 119.4.250.168 () {40 vars in 845 bytes} [Mon Feb 18 12:08:42 2019] GET / => generated 3014 bytes in 2633 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 2/6] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:08:49 2019] GET / => generated 3014 bytes in 2328 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 3/7] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:08:57 2019] GET / => generated 3014 bytes in 2195 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 4/8] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:09:29 2019] GET / => generated 3023 bytes in 11327 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 5/9] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:10:12 2019] GET / => generated 3014 bytes in 2460 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 5/10] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:19:27 2019] GET / => generated 3023 bytes in 9914 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 7/11] 170.245.131.118 () {32 vars in 453 bytes} [Mon Feb 18 12:20:22 2019] GET / => generated 3023 bytes in 11312 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 7/12] 119.4.250.168 () {42 vars in 876 bytes} [Mon Feb 18 12:20:22 2019] GET / => generated 3023 bytes in 11497 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 8/13] 119.4.250.168 () {40 vars in 845 bytes} [Mon Feb 18 12:27:26 2019] GET / => generated 3014 bytes in 3594 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 6/14] 119.4.250.168 () {38 vars in 650 bytes} [Mon Feb 18 12:27:30 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 7/15] 119.4.250.169 () {42 vars in 874 bytes} [Mon Feb 18 12:29:00 2019] GET / => generated 3023 bytes in 11222 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 8/16] 119.4.250.169 () {40 vars in 704 bytes} [Mon Feb 18 12:29:12 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Invalid HTTP_HOST header: 'clientapi.ipip.net'. You may need to add 'clientapi.ipip.net' to ALLOWED_HOSTS.
Bad Request: /echo.php
[pid: 4029|app: 0|req: 9/17] 139.162.88.63 () {32 vars in 408 bytes} [Mon Feb 18 12:47:35 2019] GET /echo.php?info=1234567890 => generated 55083 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 9/18] 179.113.95.86 () {32 vars in 452 bytes} [Mon Feb 18 13:31:22 2019] GET / => generated 3014 bytes in 15512 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 10/19] 172.104.108.109 () {34 vars in 379 bytes} [Mon Feb 18 13:48:05 2019] GET / => generated 3014 bytes in 3729 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Invalid HTTP_HOST header: 'clientapi.ipip.net'. You may need to add 'clientapi.ipip.net' to ALLOWED_HOSTS.
Bad Request: /echo.php
[pid: 4029|app: 0|req: 11/20] 172.104.108.109 () {34 vars in 453 bytes} [Mon Feb 18 13:48:09 2019] GET /echo.php?info=20190218134808 => generated 55260 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 4030|app: 0|req: 10/21] 106.39.190.78 () {48 vars in 977 bytes} [Mon Feb 18 15:25:25 2019] GET / => generated 3014 bytes in 4910 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 11/22] 119.4.250.169 () {38 vars in 661 bytes} [Mon Feb 18 15:25:31 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 12/23] 119.4.250.169 () {44 vars in 905 bytes} [Mon Feb 18 15:30:26 2019] GET / => generated 3014 bytes in 4098 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 12/24] 179.189.202.32 () {32 vars in 459 bytes} [Mon Feb 18 15:33:41 2019] GET / => generated 3023 bytes in 7016 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 13/25] 197.255.185.36 () {32 vars in 453 bytes} [Mon Feb 18 16:01:37 2019] GET / => generated 3023 bytes in 15598 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 13/26] 77.159.67.216 () {32 vars in 451 bytes} [Mon Feb 18 16:03:36 2019] GET / => generated 3023 bytes in 11271 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 14/27] 119.4.250.168 () {40 vars in 845 bytes} [Mon Feb 18 16:37:43 2019] GET / => generated 3009 bytes in 4749 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 15/28] 119.4.250.168 () {38 vars in 675 bytes} [Mon Feb 18 16:37:48 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 14/29] 119.4.250.168 () {40 vars in 845 bytes} [Mon Feb 18 17:19:52 2019] GET / => generated 3009 bytes in 4871 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 15/30] 119.4.250.168 () {38 vars in 650 bytes} [Mon Feb 18 17:19:59 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 16/31] 47.93.180.168 () {26 vars in 269 bytes} [Mon Feb 18 17:22:49 2019] GET / => generated 54002 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 16/32] 177.64.52.52 () {26 vars in 268 bytes} [Mon Feb 18 17:24:58 2019] GET / => generated 54001 bytes in 31 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 17/33] 109.230.74.59 () {26 vars in 269 bytes} [Mon Feb 18 18:47:00 2019] GET / => generated 54002 bytes in 30 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 18/34] 205.205.150.14 () {32 vars in 419 bytes} [Mon Feb 18 18:54:40 2019] HEAD / => generated 3009 bytes in 4701 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 17/35] 205.205.150.14 () {32 vars in 419 bytes} [Mon Feb 18 18:55:20 2019] HEAD / => generated 3009 bytes in 1971 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 19/36] 78.165.239.10 () {32 vars in 451 bytes} [Mon Feb 18 19:00:17 2019] GET / => generated 3009 bytes in 3386 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 18/37] 190.190.108.154 () {26 vars in 271 bytes} [Mon Feb 18 19:28:00 2019] GET / => generated 54004 bytes in 31 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 20/38] 201.26.98.129 () {32 vars in 458 bytes} [Mon Feb 18 20:22:08 2019] GET / => generated 3009 bytes in 4465 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 21/39] 151.64.21.175 () {32 vars in 458 bytes} [Mon Feb 18 20:48:57 2019] GET / => generated 3009 bytes in 2858 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Invalid HTTP_HOST header: 'check.proxyradar.com'. You may need to add 'check.proxyradar.com' to ALLOWED_HOSTS.
Bad Request: /azenv.php
[pid: 4030|app: 0|req: 22/40] 95.213.177.123 () {40 vars in 694 bytes} [Mon Feb 18 20:58:00 2019] POST /azenv.php?auth=155052348015&a=PSCN&i=661260957&p=80 => generated 57035 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 19/41] 185.78.32.111 () {32 vars in 458 bytes} [Mon Feb 18 21:10:57 2019] GET / => generated 3009 bytes in 5689 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 4030|app: 0|req: 23/42] 80.82.70.187 () {32 vars in 421 bytes} [Mon Feb 18 21:20:13 2019] GET /cache/global/img/gs.gif => generated 54787 bytes in 29 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 20/43] 124.218.132.144 () {26 vars in 271 bytes} [Mon Feb 18 22:12:01 2019] GET / => generated 54004 bytes in 31 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 21/44] 78.139.61.32 () {32 vars in 451 bytes} [Mon Feb 18 22:38:54 2019] GET / => generated 3009 bytes in 4586 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 4030|app: 0|req: 24/45] 59.36.132.222 () {34 vars in 468 bytes} [Mon Feb 18 22:46:45 2019] GET / => generated 54722 bytes in 31 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 25/46] 177.223.107.15 () {32 vars in 452 bytes} [Tue Feb 19 00:03:40 2019] GET / => generated 3009 bytes in 10750 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 26/47] 51.38.12.21 () {32 vars in 436 bytes} [Tue Feb 19 00:22:03 2019] GET / => generated 3009 bytes in 3391 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 22/48] 106.39.190.61 () {48 vars in 977 bytes} [Tue Feb 19 00:42:46 2019] GET / => generated 3009 bytes in 5174 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 27/49] 119.4.250.167 () {38 vars in 675 bytes} [Tue Feb 19 00:42:52 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 23/50] 119.4.250.167 () {40 vars in 845 bytes} [Tue Feb 19 01:27:53 2019] GET / => generated 3009 bytes in 5323 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 24/51] 119.4.250.167 () {38 vars in 650 bytes} [Tue Feb 19 01:28:00 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 25/52] 47.100.64.86 () {26 vars in 268 bytes} [Tue Feb 19 01:32:40 2019] GET / => generated 54001 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 28/53] 123.27.214.26 () {26 vars in 269 bytes} [Tue Feb 19 01:35:59 2019] GET / => generated 54002 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 29/54] 109.233.196.232 () {32 vars in 454 bytes} [Tue Feb 19 01:54:23 2019] GET / => generated 3009 bytes in 3643 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 30/55] 143.202.188.63 () {32 vars in 452 bytes} [Tue Feb 19 02:13:28 2019] GET / => generated 3023 bytes in 11288 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-34:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 26/56] 106.39.190.56 () {48 vars in 977 bytes} [Tue Feb 19 02:49:35 2019] GET / => generated 3023 bytes in 14337 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 31/57] 119.4.250.167 () {38 vars in 675 bytes} [Tue Feb 19 02:49:50 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 27/58] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 02:56:26 2019] GET / => generated 3023 bytes in 11978 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 28/59] 203.189.137.200 () {32 vars in 454 bytes} [Tue Feb 19 03:00:23 2019] GET / => generated 3023 bytes in 6060 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 29/60] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 03:01:24 2019] GET / => generated 3009 bytes in 3028 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 32/61] 119.4.250.167 () {40 vars in 845 bytes} [Tue Feb 19 03:05:57 2019] GET / => generated 3023 bytes in 4416 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 33/62] 119.4.250.167 () {38 vars in 650 bytes} [Tue Feb 19 03:06:02 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 34/63] 103.49.56.14 () {32 vars in 450 bytes} [Tue Feb 19 03:16:28 2019] GET / => generated 3009 bytes in 2422 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 30/64] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 03:17:08 2019] GET / => generated 3023 bytes in 11768 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 35/65] 119.4.250.167 () {38 vars in 648 bytes} [Tue Feb 19 03:25:04 2019] GET / => generated 3009 bytes in 10258 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 31/66] 119.4.250.167 () {38 vars in 626 bytes} [Tue Feb 19 03:25:15 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Exception in thread Thread-44:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 32/67] 103.63.95.99 () {32 vars in 450 bytes} [Tue Feb 19 03:36:08 2019] GET / => generated 3023 bytes in 16378 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 36/68] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 04:28:22 2019] GET / => generated 3023 bytes in 14527 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Exception in thread Thread-48:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 37/69] 119.4.250.167 () {40 vars in 845 bytes} [Tue Feb 19 04:33:10 2019] GET / => generated 3023 bytes in 10085 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 38/70] 119.4.250.167 () {38 vars in 675 bytes} [Tue Feb 19 04:33:24 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 33/71] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 04:42:21 2019] GET / => generated 3009 bytes in 4171 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 39/72] 202.71.18.73 () {26 vars in 268 bytes} [Tue Feb 19 05:07:32 2019] GET / => generated 54001 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Forbidden (CSRF cookie not set.): /
[pid: 4029|app: 0|req: 35/73] 113.96.223.207 () {28 vars in 299 bytes} [Tue Feb 19 05:18:56 2019] OPTION / => generated 2868 bytes in 40 msecs (HTTP/1.1 403) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 35/74] 113.96.223.207 () {28 vars in 296 bytes} [Tue Feb 19 05:18:56 2019] GET / => generated 3009 bytes in 7031 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 36/75] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 05:23:14 2019] GET / => generated 3009 bytes in 3060 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 40/76] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 05:28:23 2019] GET / => generated 3009 bytes in 3541 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 41/77] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 05:33:53 2019] GET / => generated 3009 bytes in 3992 msecs (HTTP/1.0 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-54:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 42/78] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 05:41:29 2019] GET / => generated 3023 bytes in 13404 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 37/79] 84.117.200.202 () {26 vars in 270 bytes} [Tue Feb 19 05:56:03 2019] GET / => generated 54003 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 43/80] 84.117.200.202 () {26 vars in 270 bytes} [Tue Feb 19 05:56:05 2019] GET / => generated 54003 bytes in 30 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 0)
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 38/81] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:00:05 2019] GET / => generated 3023 bytes in 14204 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 14:01:19 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 4029|app: 0|req: 39/82] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:01:32 2019] GET / => generated 3012 bytes in 2569 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 40/83] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:01:50 2019] GET / => generated 3023 bytes in 11423 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 14:03:41 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 44/84] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:03:50 2019] GET / => generated 3021 bytes in 11355 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 45/85] 218.29.111.116 () {34 vars in 440 bytes} [Tue Feb 19 06:14:30 2019] GET / => generated 3021 bytes in 13067 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /index.action
[pid: 4030|app: 0|req: 46/86] 218.29.111.116 () {34 vars in 2183 bytes} [Tue Feb 19 06:14:43 2019] GET /index.action => generated 2137 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 41/87] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:20:06 2019] GET / => generated 3010 bytes in 6217 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 47/88] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:29:45 2019] GET / => generated 3021 bytes in 12735 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-60:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 42/89] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:42:40 2019] GET / => generated 3021 bytes in 14422 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 43/90] 198.108.67.16 () {34 vars in 381 bytes} [Tue Feb 19 06:47:06 2019] GET / => generated 3010 bytes in 3172 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-62:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 48/91] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 06:57:39 2019] GET / => generated 3021 bytes in 5773 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'check.proxyradar.com'. You may need to add 'check.proxyradar.com' to ALLOWED_HOSTS.
Bad Request: /azenv.php
[pid: 4030|app: 0|req: 49/92] 95.213.177.126 () {40 vars in 694 bytes} [Tue Feb 19 07:15:13 2019] POST /azenv.php?auth=155056051317&a=PSCN&i=661260957&p=80 => generated 57035 bytes in 33 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 50/93] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 07:23:59 2019] GET / => generated 3012 bytes in 5099 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 4029|app: 0|req: 44/94] 80.82.70.187 () {32 vars in 421 bytes} [Tue Feb 19 07:27:16 2019] GET /cache/global/img/gs.gif => generated 54787 bytes in 29 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Exception in thread Thread-66:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 51/95] 46.1.216.10 () {32 vars in 449 bytes} [Tue Feb 19 07:29:47 2019] GET / => generated 3021 bytes in 12685 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-64:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 45/96] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 07:43:51 2019] GET / => generated 3021 bytes in 12853 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-66:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 46/97] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:08:12 2019] GET / => generated 3021 bytes in 14788 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-68:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 47/98] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:08:29 2019] GET / => generated 3021 bytes in 11293 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 52/99] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:09:02 2019] GET / => generated 3012 bytes in 7755 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.qq.com'. You may need to add 'www.qq.com' to ALLOWED_HOSTS.
Bad Request: /404/search_children.js
[pid: 4030|app: 0|req: 53/100] 120.132.3.65 () {34 vars in 500 bytes} [Tue Feb 19 08:12:15 2019] GET /404/search_children.js => generated 54930 bytes in 33 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 54/101] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:23:04 2019] GET / => generated 3012 bytes in 3869 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 48/102] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:26:37 2019] GET / => generated 3012 bytes in 2766 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-72:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 55/103] 119.4.250.167 () {40 vars in 700 bytes} [Tue Feb 19 08:43:34 2019] GET / => generated 3021 bytes in 14220 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 49/104] 119.4.250.167 () {40 vars in 679 bytes} [Tue Feb 19 09:07:02 2019] GET / => generated 3012 bytes in 4197 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4030|app: 0|req: 56/105] 176.99.199.17 () {32 vars in 452 bytes} [Tue Feb 19 09:27:41 2019] GET / => generated 3012 bytes in 5530 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 57/106] 119.4.250.167 () {40 vars in 679 bytes} [Tue Feb 19 10:23:50 2019] GET / => generated 3012 bytes in 5169 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 50/107] 178.239.147.242 () {32 vars in 454 bytes} [Tue Feb 19 10:33:23 2019] GET / => generated 3012 bytes in 1929 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 58/108] 103.206.224.39 () {32 vars in 453 bytes} [Tue Feb 19 10:34:03 2019] GET / => generated 3021 bytes in 11207 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 18:46:32 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-76:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 51/109] 119.4.250.167 () {40 vars in 679 bytes} [Tue Feb 19 10:46:47 2019] GET / => generated 4029 bytes in 12459 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-78:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 52/110] 123.150.182.214 () {48 vars in 979 bytes} [Tue Feb 19 10:50:32 2019] GET / => generated 4029 bytes in 11353 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 53/111] 119.4.250.167 () {38 vars in 650 bytes} [Tue Feb 19 10:50:52 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /history
[pid: 4030|app: 0|req: 59/112] 119.4.250.167 () {42 vars in 896 bytes} [Tue Feb 19 10:50:54 2019] GET /history => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 60/113] 119.4.250.167 () {38 vars in 682 bytes} [Tue Feb 19 10:50:54 2019] GET /favicon.ico => generated 2134 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /history
[pid: 4030|app: 0|req: 61/114] 119.4.250.167 () {42 vars in 896 bytes} [Tue Feb 19 10:51:18 2019] GET /history => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /history
[pid: 4029|app: 0|req: 54/115] 119.4.250.167 () {44 vars in 927 bytes} [Tue Feb 19 10:52:43 2019] GET /history => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 62/116] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 10:53:25 2019] GET / => generated 4020 bytes in 3200 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 18:58:36 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Not Found: /hs
[pid: 4029|app: 0|req: 55/117] 119.4.250.167 () {38 vars in 673 bytes} [Tue Feb 19 10:58:58 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /hs/
[pid: 4029|app: 0|req: 56/118] 119.4.250.167 () {38 vars in 675 bytes} [Tue Feb 19 10:59:03 2019] GET /hs/ => generated 2110 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 57/119] 119.4.250.167 () {38 vars in 669 bytes} [Tue Feb 19 10:59:10 2019] GET / => generated 4020 bytes in 4956 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 63/120] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 10:59:18 2019] GET / => generated 4020 bytes in 1986 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /history
[pid: 4030|app: 0|req: 64/121] 119.4.250.167 () {42 vars in 896 bytes} [Tue Feb 19 10:59:31 2019] GET /history => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 19:01:52 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Not Found: /hs
[pid: 4030|app: 0|req: 65/122] 119.4.250.167 () {38 vars in 673 bytes} [Tue Feb 19 11:02:06 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 19:04:31 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-82:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 58/123] 119.4.250.167 () {40 vars in 845 bytes} [Tue Feb 19 11:04:45 2019] GET / => generated 4047 bytes in 12679 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 66/124] 119.4.250.167 () {38 vars in 650 bytes} [Tue Feb 19 11:05:02 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /templates/history.html
[pid: 4029|app: 0|req: 59/125] 119.4.250.167 () {42 vars in 926 bytes} [Tue Feb 19 11:05:06 2019] GET /templates/history.html => generated 2167 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 60/126] 119.4.250.167 () {38 vars in 697 bytes} [Tue Feb 19 11:05:06 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 61/127] 191.96.214.45 () {30 vars in 428 bytes} [Tue Feb 19 11:05:58 2019] GET / => generated 54383 bytes in 32 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
Not Found: /templates/history.html
[pid: 4030|app: 0|req: 67/128] 119.4.250.167 () {44 vars in 957 bytes} [Tue Feb 19 11:07:04 2019] GET /templates/history.html => generated 2167 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 19:09:34 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Not Found: /query/hs
[pid: 4030|app: 0|req: 68/129] 119.4.250.167 () {38 vars in 685 bytes} [Tue Feb 19 11:09:50 2019] GET /query/hs => generated 2125 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /query
[pid: 4030|app: 0|req: 69/130] 119.4.250.167 () {38 vars in 679 bytes} [Tue Feb 19 11:09:57 2019] GET /query => generated 2116 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 19:11:44 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Not Found: /query
[pid: 4029|app: 0|req: 62/131] 119.4.250.167 () {40 vars in 710 bytes} [Tue Feb 19 11:11:50 2019] GET /query => generated 2116 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /query
[pid: 4030|app: 0|req: 70/132] 119.4.250.167 () {40 vars in 710 bytes} [Tue Feb 19 11:11:55 2019] GET /query => generated 2116 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Exception in thread Thread-84:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 63/133] 119.4.250.167 () {40 vars in 845 bytes} [Tue Feb 19 11:12:48 2019] GET / => generated 4025 bytes in 12486 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 64/134] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 11:15:34 2019] GET / => generated 4016 bytes in 2133 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /hs
[pid: 4029|app: 0|req: 65/135] 119.4.250.167 () {40 vars in 849 bytes} [Tue Feb 19 11:15:42 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 71/136] 119.4.250.167 () {38 vars in 652 bytes} [Tue Feb 19 11:15:43 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /query
[pid: 4030|app: 0|req: 72/137] 119.4.250.167 () {40 vars in 855 bytes} [Tue Feb 19 11:15:49 2019] GET /query => generated 2116 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 73/138] 119.4.250.167 () {38 vars in 680 bytes} [Tue Feb 19 11:15:49 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /hs/
[pid: 4029|app: 0|req: 66/139] 119.4.250.167 () {40 vars in 851 bytes} [Tue Feb 19 11:15:57 2019] GET /hs/ => generated 2110 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Tue Feb 19 19:17:46 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-84:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 74/140] 119.4.250.167 () {42 vars in 876 bytes} [Tue Feb 19 11:18:14 2019] GET / => generated 4025 bytes in 12682 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /hs
[pid: 4029|app: 0|req: 67/141] 119.4.250.167 () {40 vars in 849 bytes} [Tue Feb 19 11:18:59 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /history
[pid: 4029|app: 0|req: 68/142] 119.4.250.167 () {40 vars in 859 bytes} [Tue Feb 19 11:19:05 2019] GET /history => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /history.html
[pid: 4029|app: 0|req: 69/143] 119.4.250.167 () {40 vars in 869 bytes} [Tue Feb 19 11:19:11 2019] GET /history.html => generated 2137 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /history.html
[pid: 4030|app: 0|req: 75/144] 119.4.250.167 () {40 vars in 869 bytes} [Tue Feb 19 11:19:38 2019] GET /history.html => generated 2137 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /acadmin.php
[pid: 4030|app: 0|req: 76/145] 198.167.223.52 () {36 vars in 585 bytes} [Tue Feb 19 11:35:36 2019] GET /acadmin.php => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Invalid HTTP_HOST header: 'clientapi.ipip.net'. You may need to add 'clientapi.ipip.net' to ALLOWED_HOSTS.
Bad Request: /echo.php
[pid: 4030|app: 0|req: 77/146] 139.162.88.63 () {32 vars in 408 bytes} [Tue Feb 19 12:30:29 2019] GET /echo.php?info=1234567890 => generated 55083 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
Not Found: /xmlrpc.php
[pid: 4029|app: 0|req: 70/147] 51.158.72.186 () {28 vars in 315 bytes} [Tue Feb 19 12:47:37 2019] GET /xmlrpc.php => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Exception in thread Thread-88:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 71/148] 41.78.216.84 () {32 vars in 457 bytes} [Tue Feb 19 12:59:14 2019] GET / => generated 4025 bytes in 14269 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 73/149] 109.162.188.52 () {32 vars in 452 bytes} [Tue Feb 19 13:13:13 2019] GET / => generated 4016 bytes in 5573 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-90:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 73/150] 109.162.188.52 () {32 vars in 453 bytes} [Tue Feb 19 13:13:14 2019] GET / => generated 4025 bytes in 5258 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 78/151] 89.47.39.40 () {32 vars in 450 bytes} [Tue Feb 19 13:32:52 2019] GET / => generated 4016 bytes in 8648 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 79/152] 101.132.126.80 () {34 vars in 468 bytes} [Tue Feb 19 13:42:36 2019] GET / => generated 4016 bytes in 4880 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 80/153] 88.248.54.88 () {26 vars in 268 bytes} [Tue Feb 19 13:59:40 2019] GET / => generated 54001 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 4030|app: 0|req: 81/154] 154.117.162.10 () {32 vars in 459 bytes} [Tue Feb 19 14:35:20 2019] GET / => generated 4016 bytes in 5979 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 74/155] 106.39.190.122 () {48 vars in 978 bytes} [Tue Feb 19 14:41:12 2019] GET / => generated 4025 bytes in 14426 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 75/156] 119.4.250.167 () {38 vars in 649 bytes} [Tue Feb 19 14:41:30 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /hs
[pid: 4029|app: 0|req: 76/157] 119.4.250.167 () {42 vars in 885 bytes} [Tue Feb 19 14:41:46 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 82/158] 119.4.250.167 () {38 vars in 676 bytes} [Tue Feb 19 14:41:46 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /hs
[pid: 4030|app: 0|req: 83/159] 119.4.250.167 () {42 vars in 885 bytes} [Tue Feb 19 14:41:51 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 84/160] 119.4.250.167 () {42 vars in 875 bytes} [Tue Feb 19 14:41:53 2019] GET / => generated 4016 bytes in 2089 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-96:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4029|app: 0|req: 77/161] 101.206.168.94 () {42 vars in 875 bytes} [Tue Feb 19 14:44:43 2019] GET / => generated 4025 bytes in 11283 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 85/162] 138.204.132.186 () {32 vars in 460 bytes} [Tue Feb 19 15:07:04 2019] GET / => generated 4016 bytes in 4948 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 78/163] 149.129.48.2 () {42 vars in 873 bytes} [Tue Feb 19 15:07:16 2019] GET / => generated 4016 bytes in 2008 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 79/164] 149.129.48.2 () {38 vars in 660 bytes} [Tue Feb 19 15:07:22 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 80/165] 149.129.48.2 () {44 vars in 904 bytes} [Tue Feb 19 15:07:25 2019] GET / => generated 4016 bytes in 1961 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Internal Server Error: /
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/python3/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/python3/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./query_net/views.py", line 8, in index
    request.get(ip)
  File "./query_net/main/get.py", line 113, in run
  File "./query_net/main/get.py", line 46, in get
    print('获取网页：请求过期')
  File "./query_net/main/get.py", line 48, in count_over
    if size <= 4100:
  File "./query_net/main/get.py", line 63, in listdata
    _over = Decimal(
IndexError: list index out of range
[pid: 4030|app: 0|req: 86/166] 149.129.48.2 () {44 vars in 904 bytes} [Tue Feb 19 15:07:32 2019] GET / => generated 75699 bytes in 10773 msecs (HTTP/1.1 500) 4 headers in 129 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 87/167] 149.129.48.2 () {42 vars in 873 bytes} [Tue Feb 19 15:08:19 2019] GET / => generated 4016 bytes in 6872 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 88/168] 149.129.48.2 () {40 vars in 703 bytes} [Tue Feb 19 15:08:28 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 81/169] 149.129.48.2 () {44 vars in 904 bytes} [Tue Feb 19 15:08:32 2019] GET / => generated 4016 bytes in 2280 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 89/170] 149.129.48.2 () {44 vars in 904 bytes} [Tue Feb 19 15:08:42 2019] GET / => generated 4016 bytes in 2031 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 82/171] 149.129.48.2 () {42 vars in 873 bytes} [Tue Feb 19 15:08:54 2019] GET / => generated 4016 bytes in 2041 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 83/172] 149.129.48.2 () {42 vars in 873 bytes} [Tue Feb 19 15:26:00 2019] GET / => generated 4016 bytes in 4041 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 84/173] 149.129.48.2 () {38 vars in 660 bytes} [Tue Feb 19 15:26:08 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Exception in thread Thread-100:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 4030|app: 0|req: 90/174] 149.129.48.2 () {44 vars in 904 bytes} [Tue Feb 19 15:47:37 2019] GET / => generated 4025 bytes in 17613 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 91/175] 119.4.253.196 () {44 vars in 905 bytes} [Tue Feb 19 15:48:04 2019] GET / => generated 4016 bytes in 4666 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 92/176] 185.196.182.109 () {32 vars in 454 bytes} [Tue Feb 19 16:22:52 2019] GET / => generated 4014 bytes in 35886 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 85/177] 123.150.182.214 () {48 vars in 979 bytes} [Tue Feb 19 16:28:22 2019] GET / => generated 4014 bytes in 1904 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 93/178] 119.4.249.150 () {38 vars in 650 bytes} [Tue Feb 19 16:28:26 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 86/179] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:28:27 2019] GET / => generated 4014 bytes in 3536 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 87/180] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:28:37 2019] GET / => generated 4014 bytes in 2809 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 88/181] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:35:04 2019] GET / => generated 4014 bytes in 3243 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /hs
[pid: 4030|app: 0|req: 94/182] 119.4.249.150 () {42 vars in 886 bytes} [Tue Feb 19 16:35:15 2019] GET /hs => generated 2107 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 95/183] 119.4.249.150 () {38 vars in 677 bytes} [Tue Feb 19 16:35:15 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 96/184] 119.4.249.150 () {40 vars in 845 bytes} [Tue Feb 19 16:41:20 2019] GET / => generated 4014 bytes in 5828 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 89/185] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:41:31 2019] GET / => generated 4014 bytes in 2130 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 97/186] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:41:36 2019] GET / => generated 4014 bytes in 2748 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 90/187] 119.4.249.150 () {42 vars in 876 bytes} [Tue Feb 19 16:41:41 2019] GET / => generated 4014 bytes in 2080 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Invalid HTTP_HOST header: 'check.proxyradar.com'. You may need to add 'check.proxyradar.com' to ALLOWED_HOSTS.
Bad Request: /azenv.php
[pid: 4029|app: 0|req: 91/188] 95.213.177.124 () {40 vars in 694 bytes} [Tue Feb 19 16:55:15 2019] POST /azenv.php?auth=155059531463&a=PSCN&i=661260957&p=80 => generated 57035 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 92/189] 120.55.13.109 () {26 vars in 269 bytes} [Tue Feb 19 17:18:54 2019] GET / => generated 54002 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 4030|app: 0|req: 98/190] 80.82.70.187 () {32 vars in 421 bytes} [Tue Feb 19 17:32:12 2019] GET /cache/global/img/gs.gif => generated 54787 bytes in 31 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 99/191] 77.159.80.81 () {32 vars in 450 bytes} [Tue Feb 19 19:07:25 2019] GET / => generated 4016 bytes in 4831 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 93/192] 104.131.146.18 () {34 vars in 382 bytes} [Tue Feb 19 19:49:36 2019] GET / => generated 4016 bytes in 4900 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 100/193] 205.205.150.14 () {34 vars in 443 bytes} [Tue Feb 19 20:25:28 2019] GET / => generated 4016 bytes in 4676 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 94/194] 205.205.150.14 () {34 vars in 443 bytes} [Tue Feb 19 20:25:29 2019] GET / => generated 4016 bytes in 4650 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 101/195] 47.93.180.168 () {26 vars in 269 bytes} [Tue Feb 19 21:32:49 2019] GET / => generated 54002 bytes in 31 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4030|app: 0|req: 102/196] 220.135.69.213 () {26 vars in 270 bytes} [Tue Feb 19 22:01:27 2019] GET / => generated 54003 bytes in 32 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 103/197] 2.181.77.61 () {32 vars in 456 bytes} [Tue Feb 19 22:19:31 2019] GET / => generated 4016 bytes in 5075 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 95/198] 2.181.77.61 () {32 vars in 449 bytes} [Tue Feb 19 22:19:32 2019] GET / => generated 4016 bytes in 5597 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 104/199] 188.169.178.50 () {32 vars in 453 bytes} [Tue Feb 19 23:41:25 2019] GET / => generated 4016 bytes in 4647 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 96/200] 105.247.248.226 () {32 vars in 460 bytes} [Wed Feb 20 00:43:39 2019] GET / => generated 4016 bytes in 5026 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 97/201] 191.205.101.166 () {32 vars in 453 bytes} [Wed Feb 20 02:01:15 2019] GET / => generated 4016 bytes in 5702 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 105/202] 201.92.45.47 () {32 vars in 451 bytes} [Wed Feb 20 02:19:37 2019] GET / => generated 4016 bytes in 4468 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 106/203] 123.150.183.205 () {48 vars in 979 bytes} [Wed Feb 20 02:33:27 2019] GET / => generated 4016 bytes in 5284 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 107/204] 119.4.249.150 () {38 vars in 649 bytes} [Wed Feb 20 02:33:36 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4030|app: 0|req: 108/205] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 02:36:44 2019] GET / => generated 4016 bytes in 2326 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 98/206] 119.4.249.150 () {40 vars in 844 bytes} [Wed Feb 20 02:58:23 2019] GET / => generated 4016 bytes in 3452 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Not Found: /favicon.ico
[pid: 4029|app: 0|req: 99/207] 119.4.249.150 () {38 vars in 674 bytes} [Wed Feb 20 02:58:27 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 100/208] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 02:58:31 2019] GET / => generated 4016 bytes in 2104 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'check.proxyradar.com'. You may need to add 'check.proxyradar.com' to ALLOWED_HOSTS.
Bad Request: /azenv.php
[pid: 4030|app: 0|req: 109/209] 95.213.177.126 () {40 vars in 694 bytes} [Wed Feb 20 03:07:41 2019] POST /azenv.php?auth=155063206199&a=PSCN&i=661260957&p=80 => generated 57035 bytes in 33 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 110/210] 119.4.249.150 () {38 vars in 647 bytes} [Wed Feb 20 03:11:50 2019] GET / => generated 4016 bytes in 5604 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Not Found: /favicon.ico
[pid: 4030|app: 0|req: 111/211] 119.4.249.150 () {38 vars in 625 bytes} [Wed Feb 20 03:11:58 2019] GET /favicon.ico => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 101/212] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 03:15:29 2019] GET / => generated 4016 bytes in 2873 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4030|app: 0|req: 112/213] 175.100.66.229 () {32 vars in 452 bytes} [Wed Feb 20 03:16:11 2019] GET / => generated 4016 bytes in 3551 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Not Found: /spa2102.cfg
[pid: 4029|app: 0|req: 102/214] 62.173.154.74 () {32 vars in 442 bytes} [Wed Feb 20 03:30:45 2019] GET /spa2102.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /spa3102.cfg
[pid: 4029|app: 0|req: 103/215] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:46 2019] GET /spa3102.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /spa921.cfg
[pid: 4029|app: 0|req: 104/216] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:46 2019] GET /spa921.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /spa941.cfg
[pid: 4030|app: 0|req: 113/217] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:47 2019] GET /spa941.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /spa942.cfg
[pid: 4030|app: 0|req: 114/218] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:47 2019] GET /spa942.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /spa112.cfg
[pid: 4030|app: 0|req: 115/219] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:47 2019] GET /spa112.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /spa122.cfg
[pid: 4029|app: 0|req: 105/220] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:47 2019] GET /spa122.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /spa301.cfg
[pid: 4030|app: 0|req: 116/221] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:48 2019] GET /spa301.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /spa303.cfg
[pid: 4029|app: 0|req: 106/222] 62.173.154.74 () {30 vars in 411 bytes} [Wed Feb 20 03:30:48 2019] GET /spa303.cfg => generated 2131 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /spa501g.cfg
[pid: 4029|app: 0|req: 107/223] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:48 2019] GET /spa501g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /spa502g.cfg
[pid: 4029|app: 0|req: 108/224] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:48 2019] GET /spa502g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /spa504g.cfg
[pid: 4030|app: 0|req: 117/225] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:48 2019] GET /spa504g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
Not Found: /spa508g.cfg
[pid: 4030|app: 0|req: 118/226] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:49 2019] GET /spa508g.cfg => generated 2134 bytes in 5 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 2)
Not Found: /spa509g.cfg
[pid: 4030|app: 0|req: 119/227] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:49 2019] GET /spa509g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Not Found: /spa512g.cfg
[pid: 4029|app: 0|req: 109/228] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:49 2019] GET /spa512g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /spa525g.cfg
[pid: 4030|app: 0|req: 120/229] 62.173.154.74 () {30 vars in 413 bytes} [Wed Feb 20 03:30:49 2019] GET /spa525g.cfg => generated 2134 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
Not Found: /spa525g2.cfg
[pid: 4029|app: 0|req: 110/230] 62.173.154.74 () {30 vars in 415 bytes} [Wed Feb 20 03:30:50 2019] GET /spa525g2.cfg => generated 2137 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 3)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /cache/global/img/gs.gif
[pid: 4029|app: 0|req: 111/231] 80.82.70.187 () {32 vars in 421 bytes} [Wed Feb 20 03:36:32 2019] GET /cache/global/img/gs.gif => generated 54787 bytes in 31 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 4029|app: 0|req: 112/232] 36.66.211.63 () {32 vars in 451 bytes} [Wed Feb 20 04:01:02 2019] GET / => generated 4016 bytes in 6880 msecs (HTTP/1.0 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 121/233] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 04:12:45 2019] GET / => generated 4016 bytes in 3770 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 122/234] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 04:12:53 2019] GET / => generated 4016 bytes in 3533 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 4030|app: 0|req: 123/235] 137.74.30.53 () {32 vars in 437 bytes} [Wed Feb 20 04:13:59 2019] GET / => generated 4016 bytes in 2297 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 4029|app: 0|req: 113/236] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 04:15:52 2019] GET / => generated 4016 bytes in 2146 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 12:16:45 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 4030|app: 0|req: 124/237] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 04:17:02 2019] GET / => generated 3962 bytes in 2419 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 114/238] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 04:17:08 2019] GET / => generated 3962 bytes in 2145 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Invalid HTTP_HOST header: '_'. The domain name provided is not valid according to RFC 1034/1035.
Bad Request: /
[pid: 4029|app: 0|req: 115/239] 121.74.176.110 () {26 vars in 270 bytes} [Wed Feb 20 04:20:05 2019] GET / => generated 54003 bytes in 29 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 2)
Invalid HTTP_HOST header: 'www.baidu.com'. You may need to add 'www.baidu.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 4029|app: 0|req: 116/240] 58.19.92.49 () {36 vars in 463 bytes} [Wed Feb 20 04:42:35 2019] GET / => generated 54807 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'www.rfa.org'. You may need to add 'www.rfa.org' to ALLOWED_HOSTS.
Bad Request: /
[pid: 4030|app: 0|req: 125/241] 58.19.92.49 () {36 vars in 461 bytes} [Wed Feb 20 04:42:41 2019] GET / => generated 54775 bytes in 30 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
Invalid HTTP_HOST header: 'wujieliulan.com'. You may need to add 'wujieliulan.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 4030|app: 0|req: 126/242] 58.19.92.49 () {36 vars in 465 bytes} [Wed Feb 20 04:42:41 2019] GET / => generated 54837 bytes in 29 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
Invalid HTTP_HOST header: 'www.minghui.org'. You may need to add 'www.minghui.org' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.epochtimes.com'. You may need to add 'www.epochtimes.com' to ALLOWED_HOSTS.
Invalid HTTP_HOST header: 'www.boxun.com'. You may need to add 'www.boxun.com' to ALLOWED_HOSTS.
Bad Request: /
[pid: 4029|app: 0|req: 117/243] 58.19.92.49 () {36 vars in 468 bytes} [Wed Feb 20 04:42:41 2019] GET / => generated 54882 bytes in 63 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
Bad Request: /
[pid: 4030|app: 0|req: 128/244] 58.19.92.49 () {36 vars in 465 bytes} [Wed Feb 20 04:42:41 2019] GET / => generated 54837 bytes in 83 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
Bad Request: /
[pid: 4030|app: 0|req: 128/245] 58.19.92.49 () {36 vars in 463 bytes} [Wed Feb 20 04:42:41 2019] GET / => generated 54807 bytes in 84 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
[pid: 4029|app: 0|req: 118/246] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:00:48 2019] GET / => generated 3962 bytes in 5126 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:05:08 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 4029|app: 0|req: 119/247] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:05:16 2019] GET / => generated 3986 bytes in 2101 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Not Found: /hs.html
[pid: 4030|app: 0|req: 129/248] 119.4.249.150 () {40 vars in 719 bytes} [Wed Feb 20 05:05:25 2019] GET /hs.html => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 1)
[pid: 4030|app: 0|req: 130/249] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:07:06 2019] GET / => generated 3986 bytes in 4172 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:11:27 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 4029|app: 0|req: 120/250] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:11:40 2019] GET / => generated 3986 bytes in 2291 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:14:17 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 4030|app: 0|req: 131/251] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:15:03 2019] GET / => generated 3986 bytes in 5533 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Not Found: /hs.html
[pid: 4030|app: 0|req: 132/252] 119.4.249.150 () {40 vars in 719 bytes} [Wed Feb 20 05:15:11 2019] GET /hs.html => generated 2122 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 102 bytes (1 switches on core 0)
...brutally killing workers...
[deadlock-detector] a process holding a robust mutex died. recovering...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/django/web/untitled
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /startic => /home/web/django/web/untitled/static
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 05:28:18 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x15d5fd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x15d5fd0 pid: 4028 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4028)
spawned uWSGI worker 1 (pid: 7240, cores: 4)
spawned uWSGI worker 2 (pid: 7241, cores: 4)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:29:08 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7240|app: 0|req: 1/1] 119.4.249.150 () {38 vars in 647 bytes} [Wed Feb 20 05:29:19 2019] GET / => generated 3992 bytes in 5249 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 1/2] 119.4.249.150 () {40 vars in 732 bytes} [Wed Feb 20 05:29:34 2019] GET /hs.html => generated 77 bytes in 103 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 2/3] 119.4.249.150 () {40 vars in 732 bytes} [Wed Feb 20 05:29:50 2019] GET /hs.html => generated 77 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:43:09 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7240|app: 0|req: 3/4] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:43:19 2019] GET / => generated 3992 bytes in 8383 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 4/5] 119.4.249.150 () {40 vars in 719 bytes} [Wed Feb 20 05:43:32 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 2/6] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 05:44:35 2019] GET / => generated 4045 bytes in 2123 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 3/7] 119.4.249.150 () {40 vars in 698 bytes} [Wed Feb 20 05:44:41 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:45:54 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7241|app: 0|req: 4/8] 119.4.249.150 () {42 vars in 729 bytes} [Wed Feb 20 05:46:04 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 5/9] 119.4.249.150 () {38 vars in 651 bytes} [Wed Feb 20 05:46:09 2019] GET /hs => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 109 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 5/10] 119.4.249.150 () {38 vars in 653 bytes} [Wed Feb 20 05:46:10 2019] GET /hs/ => generated 124927 bytes in 3 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 6/11] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 05:46:11 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550641571771 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7240|app: 0|req: 7/12] 119.4.249.150 () {38 vars in 668 bytes} [Wed Feb 20 05:46:26 2019] GET / => generated 3992 bytes in 2468 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:50:03 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7240|app: 0|req: 8/13] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 05:50:13 2019] GET / => generated 3992 bytes in 8691 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 6/14] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:50:29 2019] GET / => generated 4045 bytes in 2246 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 7/15] 119.4.249.150 () {40 vars in 719 bytes} [Wed Feb 20 05:50:34 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:51:28 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7241|app: 0|req: 8/16] 119.4.249.150 () {40 vars in 699 bytes} [Wed Feb 20 05:51:35 2019] GET / => generated 4045 bytes in 2194 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 9/17] 119.4.249.150 () {40 vars in 719 bytes} [Wed Feb 20 05:51:44 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 9/18] 119.4.249.150 () {38 vars in 674 bytes} [Wed Feb 20 05:51:49 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 10/19] 119.4.249.150 () {46 vars in 925 bytes} [Wed Feb 20 05:51:51 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550641910894 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7240|app: 0|req: 11/20] 119.4.249.150 () {38 vars in 647 bytes} [Wed Feb 20 05:52:02 2019] GET / => generated 3992 bytes in 2161 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 12/21] 119.4.249.150 () {40 vars in 698 bytes} [Wed Feb 20 05:52:25 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 10/22] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 05:52:29 2019] GET / => generated 4045 bytes in 2253 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 11/23] 119.4.249.150 () {40 vars in 698 bytes} [Wed Feb 20 05:52:35 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7241|app: 0|req: 12/24] 119.4.249.150 () {38 vars in 653 bytes} [Wed Feb 20 05:52:41 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 13/25] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 05:52:42 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550641962390 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 13/26] 119.4.249.150 () {38 vars in 653 bytes} [Wed Feb 20 05:53:25 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 14/27] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 05:53:27 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550642007020 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7240|app: 0|req: 15/28] 123.150.182.214 () {48 vars in 979 bytes} [Wed Feb 20 05:53:50 2019] GET / => generated 3992 bytes in 2359 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 16/29] 119.4.249.150 () {38 vars in 649 bytes} [Wed Feb 20 05:53:55 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 14/30] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 05:53:57 2019] GET / => generated 4045 bytes in 2147 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 15/31] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 05:54:01 2019] GET / => generated 4045 bytes in 2237 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7241|app: 0|req: 16/32] 119.4.249.150 () {42 vars in 895 bytes} [Wed Feb 20 05:54:05 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 17/33] 119.4.249.150 () {38 vars in 681 bytes} [Wed Feb 20 05:54:05 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 17/34] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 05:54:15 2019] GET / => generated 4045 bytes in 2186 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 18/35] 119.4.249.150 () {38 vars in 673 bytes} [Wed Feb 20 05:55:01 2019] GET /hs/ => generated 124927 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7240|app: 0|req: 19/36] 119.4.249.150 () {46 vars in 924 bytes} [Wed Feb 20 05:55:02 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550642102275 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7240|app: 0|req: 20/37] 119.4.249.150 () {38 vars in 653 bytes} [Wed Feb 20 05:55:55 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7241|app: 0|req: 18/38] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 05:55:57 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550642156593 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 13:57:05 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7241|app: 0|req: 19/39] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:03:16 2019] GET / => generated 4045 bytes in 4606 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7241|app: 0|req: 20/40] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:05:52 2019] GET / => generated 4045 bytes in 3146 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 14:06:06 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7240|app: 0|req: 21/41] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:06:13 2019] GET / => generated 3992 bytes in 2051 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7241|app: 0|req: 21/42] 119.4.249.150 () {42 vars in 895 bytes} [Wed Feb 20 06:06:20 2019] GET /hs.html => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7240|app: 0|req: 22/43] 119.4.249.150 () {38 vars in 681 bytes} [Wed Feb 20 06:06:20 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 14:08:34 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
...brutally killing workers...
[deadlock-detector] a process holding a robust mutex died. recovering...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/django/web/untitled
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/django/web/untitled
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (/home/web/django/web/untitled/uwsgi.sock)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /startic => /home/web/django/web/untitled/static
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 06:13:22 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /startic => /home/web/django/web/untitled/static
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 06:13:22 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
VACUUM: pidfile removed.
Python main interpreter initialized at 0x246ffd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x246ffd0 pid: 4028 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4028)
spawned uWSGI worker 1 (pid: 7491, cores: 4)
spawned uWSGI worker 2 (pid: 7492, cores: 4)
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
binary reloading uWSGI...
chdir() to /home/web/django/web/untitled
closing all non-uwsgi socket fds > 2 (max_fd = 65535)...
found fd 3 mapped to socket 0 (127.0.0.1:8888)
running /usr/local/python3/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
[uwsgi-static] added mapping for /startic => /home/web/django/web/untitled/static
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 06:13:35 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 inherited INET address 127.0.0.1:8888 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.2 (default, Jan 13 2019, 18:54:12)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Python main interpreter initialized at 0x1de8fd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 312864 bytes (305 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x1de8fd0 pid: 4028 (default app)
mountpoint  already configured. skip.
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 4028)
spawned uWSGI worker 1 (pid: 7501, cores: 4)
spawned uWSGI worker 2 (pid: 7502, cores: 4)
[pid: 7501|app: 0|req: 1/1] 119.4.249.150 () {38 vars in 647 bytes} [Wed Feb 20 06:21:51 2019] GET / => generated 3816 bytes in 5809 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 1/2] 119.4.249.150 () {40 vars in 710 bytes} [Wed Feb 20 06:22:22 2019] GET /hs/ => generated 124927 bytes in 103 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 2/3] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:22:35 2019] GET / => generated 3816 bytes in 3157 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 3/4] 119.4.249.150 () {42 vars in 885 bytes} [Wed Feb 20 06:22:39 2019] GET /hs => generated 0 bytes in 1 msecs (HTTP/1.1 301) 3 headers in 109 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 4/5] 119.4.249.150 () {42 vars in 887 bytes} [Wed Feb 20 06:22:39 2019] GET /hs/ => generated 124927 bytes in 2 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 2/6] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:22:43 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643763069 => generated 77 bytes in 3 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 3/7] 119.4.249.150 () {38 vars in 677 bytes} [Wed Feb 20 06:22:44 2019] GET /favicon.ico => generated 77 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 4/8] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:22:47 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 5/9] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:22:48 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643768294 => generated 77 bytes in 2 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 5/10] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:22:48 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 6/11] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:22:50 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643770019 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 7/12] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:22:50 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 8/13] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:22:51 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643771744 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 6/14] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:24:47 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 7/15] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:24:48 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643888636 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 8/16] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:24:50 2019] GET / => generated 3816 bytes in 2757 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 9/17] 119.4.249.150 () {42 vars in 887 bytes} [Wed Feb 20 06:25:12 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 9/18] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:25:13 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550643913635 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 10/19] 119.4.249.150 () {38 vars in 677 bytes} [Wed Feb 20 06:25:13 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 14:26:21 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7501|app: 0|req: 11/20] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:26:27 2019] GET / => generated 3816 bytes in 2326 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 12/21] 119.4.249.150 () {42 vars in 887 bytes} [Wed Feb 20 06:26:41 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 10/22] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:26:41 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550644001954 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 11/23] 119.4.249.150 () {38 vars in 677 bytes} [Wed Feb 20 06:26:42 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 12/24] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:26:42 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 13/25] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:26:43 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550644003899 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 13/26] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:26:44 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 14/27] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:26:45 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550644005592 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 15/28] 119.4.249.150 () {42 vars in 875 bytes} [Wed Feb 20 06:26:48 2019] GET / => generated 3816 bytes in 2128 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 16/29] 119.4.249.150 () {40 vars in 712 bytes} [Wed Feb 20 06:34:48 2019] GET / => generated 3816 bytes in 3483 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 14/30] 119.4.249.150 () {40 vars in 690 bytes} [Wed Feb 20 06:35:04 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 15/31] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:35:07 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550644507329 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 16/32] 119.4.249.150 () {40 vars in 690 bytes} [Wed Feb 20 06:45:19 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 17/33] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:45:21 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645121215 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 17/34] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 06:45:44 2019] GET / => generated 3816 bytes in 5454 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 18/35] 119.4.249.150 () {40 vars in 690 bytes} [Wed Feb 20 06:46:04 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 19/36] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:46:05 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645165538 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 20/37] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:46:21 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 18/38] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:46:22 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645182664 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 19/39] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:46:23 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 20/40] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:46:24 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645184302 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 21/41] 119.4.249.150 () {40 vars in 690 bytes} [Wed Feb 20 06:47:08 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 21/42] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:47:10 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645229200 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 22/43] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:47:11 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 23/44] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:47:12 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645232751 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 24/45] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 06:47:29 2019] GET / => generated 3816 bytes in 2616 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 22/46] 119.4.249.150 () {40 vars in 690 bytes} [Wed Feb 20 06:47:36 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 23/47] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:47:37 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645257350 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 24/48] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:47:40 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 25/49] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:47:41 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645261104 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 25/50] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:48:15 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 26/51] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:48:16 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645296544 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 27/52] 119.4.249.150 () {42 vars in 721 bytes} [Wed Feb 20 06:48:19 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 28/53] 119.4.249.150 () {46 vars in 904 bytes} [Wed Feb 20 06:48:20 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645300340 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 26/54] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 06:48:43 2019] GET / => generated 3816 bytes in 8404 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 27/55] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 06:49:09 2019] GET / => generated 3816 bytes in 3140 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 28/56] 119.4.249.150 () {40 vars in 844 bytes} [Wed Feb 20 06:56:15 2019] GET / => generated 3816 bytes in 7551 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 29/57] 119.4.249.150 () {38 vars in 674 bytes} [Wed Feb 20 06:56:24 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 29/58] 119.4.249.150 () {42 vars in 887 bytes} [Wed Feb 20 06:56:29 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 30/59] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:56:30 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645790077 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 31/60] 119.4.249.150 () {38 vars in 677 bytes} [Wed Feb 20 06:56:30 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 32/61] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:56:34 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 30/62] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:56:35 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645795769 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 31/63] 119.4.249.150 () {44 vars in 918 bytes} [Wed Feb 20 06:56:37 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 32/64] 119.4.249.150 () {46 vars in 964 bytes} [Wed Feb 20 06:56:38 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550645798228 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 33/65] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 07:00:07 2019] GET / => generated 3816 bytes in 4464 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 33/66] 119.4.249.150 () {40 vars in 678 bytes} [Wed Feb 20 07:07:38 2019] GET / => generated 3816 bytes in 8713 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 34/67] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:11:21 2019] GET / => generated 3816 bytes in 2902 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 35/68] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:14:15 2019] GET / => generated 3816 bytes in 3583 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 36/69] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:14:21 2019] GET / => generated 3816 bytes in 2553 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 34/70] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 07:14:30 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 35/71] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 07:14:31 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550646871303 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 36/72] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:15:31 2019] GET / => generated 3816 bytes in 2181 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 37/73] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 07:15:40 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 37/74] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 07:15:41 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550646940905 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 38/75] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:17:39 2019] GET / => generated 3816 bytes in 2119 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 39/76] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 07:17:49 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 40/77] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 07:17:50 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550647070578 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 38/78] 119.4.249.150 () {42 vars in 722 bytes} [Wed Feb 20 07:17:54 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 39/79] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 07:17:56 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550647075955 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 40/80] 119.4.249.150 () {42 vars in 722 bytes} [Wed Feb 20 07:18:08 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 41/81] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 07:18:09 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550647089024 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 41/82] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:18:38 2019] GET / => generated 3816 bytes in 2343 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 42/83] 119.4.249.150 () {40 vars in 845 bytes} [Wed Feb 20 07:20:05 2019] GET / => generated 3816 bytes in 3487 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 43/84] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 07:20:10 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 44/85] 119.4.249.150 () {42 vars in 888 bytes} [Wed Feb 20 07:20:17 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 42/86] 119.4.249.150 () {46 vars in 965 bytes} [Wed Feb 20 07:20:18 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550647218371 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 43/87] 119.4.249.150 () {38 vars in 678 bytes} [Wed Feb 20 07:20:18 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 44/88] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 07:20:21 2019] GET / => generated 3816 bytes in 2488 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 45/89] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 07:20:26 2019] GET / => generated 3816 bytes in 2327 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 45/90] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 07:20:31 2019] GET / => generated 3816 bytes in 3354 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 46/91] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 07:28:26 2019] GET / => generated 3816 bytes in 5752 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 47/92] 191.8.105.213 () {32 vars in 457 bytes} [Wed Feb 20 07:29:11 2019] GET / => generated 3816 bytes in 2512 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 46/93] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 08:23:06 2019] GET / => generated 3816 bytes in 5218 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 47/94] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 08:23:35 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 48/95] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 08:23:37 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550651016930 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 48/96] 47.97.192.46 () {34 vars in 466 bytes} [Wed Feb 20 08:27:12 2019] GET / => generated 3816 bytes in 2347 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 49/97] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 08:46:51 2019] GET / => generated 3816 bytes in 3602 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 49/98] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 08:51:19 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550652678720 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 50/99] 139.162.88.63 () {32 vars in 408 bytes} [Wed Feb 20 09:06:31 2019] GET /echo.php?info=1234567890 => generated 26 bytes in 14 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
Exception in thread Thread-36:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 51/100] 47.92.115.203 () {34 vars in 486 bytes} [Wed Feb 20 09:06:42 2019] GET / => generated 3819 bytes in 14879 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 50/101] 119.4.249.150 () {38 vars in 626 bytes} [Wed Feb 20 10:05:16 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 51/102] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 10:05:17 2019] GET / => generated 3819 bytes in 15979 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 52/103] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 10:05:42 2019] GET / => generated 3819 bytes in 11243 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 52/104] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 10:07:56 2019] GET / => generated 3816 bytes in 2826 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-32:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 53/105] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 10:43:54 2019] GET / => generated 3819 bytes in 14486 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 53/106] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 10:44:11 2019] GET / => generated 3816 bytes in 2093 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 54/107] 220.135.192.179 () {26 vars in 271 bytes} [Wed Feb 20 11:40:10 2019] GET / => generated 26 bytes in 10 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 54/108] 103.96.51.202 () {32 vars in 458 bytes} [Wed Feb 20 11:56:05 2019] GET / => generated 3816 bytes in 5559 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 55/109] 71.6.232.4 () {34 vars in 472 bytes} [Wed Feb 20 12:05:06 2019] GET / => generated 3816 bytes in 4083 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 56/110] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:35:38 2019] GET / => generated 3819 bytes in 12674 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-42:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 55/111] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:35:55 2019] GET / => generated 3819 bytes in 7288 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 20:37:16 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-40:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 57/112] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:37:23 2019] GET / => generated 3819 bytes in 11462 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 56/113] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 12:37:38 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 57/114] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 12:37:40 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550666260410 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 58/115] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:38:27 2019] GET / => generated 3816 bytes in 2461 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 58/116] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:38:46 2019] GET / => generated 3816 bytes in 2253 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 59/117] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 12:39:02 2019] GET / => generated 3816 bytes in 11432 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 60/118] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 12:39:21 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 59/119] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 12:39:22 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550666362119 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 61/120] 188.158.78.13 () {36 vars in 509 bytes} [Wed Feb 20 12:42:25 2019] GET / => generated 3819 bytes in 12920 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 60/121] 177.105.237.219 () {32 vars in 454 bytes} [Wed Feb 20 12:57:56 2019] GET / => generated 3816 bytes in 5945 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 61/122] 95.213.177.126 () {40 vars in 694 bytes} [Wed Feb 20 13:05:20 2019] POST /azenv.php?auth=155066792065&a=PSCN&i=661260957&p=80 => generated 26 bytes in 10 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 7502|app: 0|req: 62/123] 80.82.70.187 () {32 vars in 421 bytes} [Wed Feb 20 13:39:35 2019] GET /cache/global/img/gs.gif => generated 26 bytes in 14 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 21:56:10 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
[pid: 7502|app: 0|req: 63/124] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 13:56:20 2019] GET / => generated 3816 bytes in 2158 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 64/125] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 13:56:26 2019] GET / => generated 3816 bytes in 2398 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 62/126] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 13:56:34 2019] GET / => generated 3816 bytes in 2156 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 65/127] 119.4.249.150 () {40 vars in 691 bytes} [Wed Feb 20 13:56:41 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 63/128] 119.4.249.150 () {46 vars in 905 bytes} [Wed Feb 20 13:56:43 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550671003208 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
Exception in thread Thread-50:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 64/129] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 13:57:05 2019] GET / => generated 3819 bytes in 11399 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
*** Starting uWSGI 2.0.17.1 (64bit) on [Wed Feb 20 21:59:52 2019] ***
compiled with version: 4.8.5 20150623 (Red Hat 4.8.5-36) on 31 January 2019 10:49:51
os: Linux-4.20.4-1.el7.elrepo.x86_64 #1 SMP Tue Jan 22 18:39:11 EST 2019
nodename: cc
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /home/web/django/web/untitled
writing pidfile to /home/web/django/web/untitled/uwsgi.pid
detected binary path: /usr/local/python3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
your processes number limit is 7883
your memory page size is 4096 bytes
detected max file descriptor number: 65535
building mime-types dictionary from file /etc/mime.types...1060 entry found
lock engine: pthread robust mutexes
thunder lock: enabled
probably another instance of uWSGI is running on the same address (127.0.0.1:8888).
bind(): Address already in use [core/socket.c line 769]
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 65/130] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 14:00:32 2019] GET / => generated 3819 bytes in 12672 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Exception in thread Thread-52:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 66/131] 119.4.249.150 () {40 vars in 679 bytes} [Wed Feb 20 14:01:05 2019] GET / => generated 3819 bytes in 11497 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 67/132] 123.150.183.205 () {48 vars in 979 bytes} [Wed Feb 20 14:03:19 2019] GET / => generated 3816 bytes in 2343 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 68/133] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 14:03:29 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 66/134] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 14:03:36 2019] GET / => generated 3816 bytes in 2271 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-56:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 69/135] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 14:04:33 2019] GET / => generated 3819 bytes in 11267 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 67/136] 119.4.249.150 () {42 vars in 888 bytes} [Wed Feb 20 14:04:50 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 68/137] 119.4.249.150 () {46 vars in 965 bytes} [Wed Feb 20 14:04:51 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550671491161 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 69/138] 119.4.249.150 () {38 vars in 678 bytes} [Wed Feb 20 14:04:51 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 70/139] 119.4.249.150 () {44 vars in 919 bytes} [Wed Feb 20 14:04:52 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 71/140] 119.4.249.150 () {46 vars in 965 bytes} [Wed Feb 20 14:04:53 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550671493510 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 72/141] 119.4.249.150 () {40 vars in 845 bytes} [Wed Feb 20 14:11:01 2019] GET / => generated 3816 bytes in 12213 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 70/142] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 14:11:15 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 73/143] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 14:11:17 2019] GET / => generated 3816 bytes in 2577 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 71/144] 119.4.249.150 () {40 vars in 845 bytes} [Wed Feb 20 15:10:05 2019] GET / => generated 3816 bytes in 4953 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 72/145] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 15:10:12 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 73/146] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 15:10:15 2019] GET / => generated 3816 bytes in 1929 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 74/147] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 15:10:19 2019] GET / => generated 3816 bytes in 1858 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 75/148] 119.4.249.150 () {40 vars in 845 bytes} [Wed Feb 20 15:16:40 2019] GET / => generated 3816 bytes in 3927 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 76/149] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 15:16:46 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 74/150] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 15:16:49 2019] GET / => generated 3816 bytes in 1920 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 77/151] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 15:16:53 2019] GET / => generated 3816 bytes in 2164 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 75/152] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 15:16:58 2019] GET / => generated 3816 bytes in 1979 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 76/153] 38.143.1.141 () {44 vars in 904 bytes} [Wed Feb 20 15:18:24 2019] GET / => generated 3816 bytes in 2063 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 77/154] 38.143.1.141 () {42 vars in 873 bytes} [Wed Feb 20 15:18:39 2019] GET / => generated 3816 bytes in 2925 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 78/155] 38.143.1.141 () {40 vars in 703 bytes} [Wed Feb 20 15:18:43 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 79/156] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:13 2019] GET / => generated 3816 bytes in 2077 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 80/157] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:16 2019] GET / => generated 3816 bytes in 1925 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 78/158] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:28 2019] GET / => generated 3816 bytes in 2256 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 81/159] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:32 2019] GET / => generated 3816 bytes in 2454 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 79/160] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:37 2019] GET / => generated 3816 bytes in 2053 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 80/161] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:19:41 2019] GET / => generated 3816 bytes in 1975 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
Exception in thread Thread-74:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 81/162] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:09 2019] GET / => generated 3819 bytes in 11205 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 82/163] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:27 2019] GET / => generated 3816 bytes in 2379 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 83/164] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:33 2019] GET / => generated 3816 bytes in 3141 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 84/165] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:37 2019] GET / => generated 3816 bytes in 1925 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 82/166] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:42 2019] GET / => generated 3816 bytes in 1873 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 85/167] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:45 2019] GET / => generated 3816 bytes in 1986 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 83/168] 101.206.167.234 () {44 vars in 907 bytes} [Wed Feb 20 15:20:50 2019] GET / => generated 3816 bytes in 2187 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 84/169] 101.206.167.234 () {42 vars in 876 bytes} [Wed Feb 20 15:21:21 2019] GET / => generated 3816 bytes in 1984 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 85/170] 101.206.167.234 () {42 vars in 876 bytes} [Wed Feb 20 15:48:26 2019] GET / => generated 3816 bytes in 4819 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 86/171] 101.206.167.234 () {40 vars in 706 bytes} [Wed Feb 20 15:48:32 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
Exception in thread Thread-82:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 87/172] 106.39.190.90 () {48 vars in 977 bytes} [Wed Feb 20 16:10:03 2019] GET / => generated 3819 bytes in 14374 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 86/173] 119.4.249.150 () {42 vars in 874 bytes} [Wed Feb 20 16:59:56 2019] GET / => generated 3816 bytes in 5042 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 88/174] 119.4.249.150 () {40 vars in 704 bytes} [Wed Feb 20 17:00:03 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 87/175] 119.4.249.150 () {44 vars in 905 bytes} [Wed Feb 20 17:00:06 2019] GET / => generated 3816 bytes in 1960 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 88/176] 119.4.249.150 () {40 vars in 845 bytes} [Wed Feb 20 17:04:22 2019] GET / => generated 3816 bytes in 2112 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 89/177] 119.4.249.150 () {38 vars in 675 bytes} [Wed Feb 20 17:04:27 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 89/178] 119.4.249.150 () {42 vars in 876 bytes} [Wed Feb 20 17:04:30 2019] GET / => generated 3816 bytes in 1942 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 90/179] 119.4.249.150 () {42 vars in 888 bytes} [Wed Feb 20 17:04:33 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 91/180] 119.4.249.150 () {46 vars in 965 bytes} [Wed Feb 20 17:04:34 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550682274345 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 90/181] 119.4.249.150 () {38 vars in 678 bytes} [Wed Feb 20 17:04:34 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 91/182] 120.78.225.124 () {26 vars in 270 bytes} [Wed Feb 20 19:30:07 2019] GET / => generated 26 bytes in 9 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 7502|app: 0|req: 92/183] 177.46.83.154 () {32 vars in 458 bytes} [Wed Feb 20 20:08:24 2019] GET / => generated 3816 bytes in 4787 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 93/184] 88.158.222.42 () {26 vars in 269 bytes} [Wed Feb 20 20:11:07 2019] GET / => generated 26 bytes in 9 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 94/185] 139.224.18.42 () {34 vars in 596 bytes} [Wed Feb 20 20:32:11 2019] GET /3D7490F9F7CCF09A6CD9583ADDE6B550.php => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7502|app: 0|req: 95/186] 180.175.139.28 () {32 vars in 357 bytes} [Wed Feb 20 21:22:40 2019] GET / => generated 26 bytes in 9 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 92/187] 60.191.52.254 () {36 vars in 572 bytes} [Wed Feb 20 21:43:55 2019] HEAD / => generated 26 bytes in 9 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 93/188] 188.209.152.216 () {36 vars in 511 bytes} [Wed Feb 20 21:44:36 2019] GET / => generated 27 bytes in 10428 msecs (HTTP/1.1 500) 4 headers in 126 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 94/189] 175.100.105.222 () {26 vars in 271 bytes} [Wed Feb 20 21:49:07 2019] GET / => generated 26 bytes in 9 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 96/190] 95.213.177.125 () {40 vars in 693 bytes} [Wed Feb 20 22:41:59 2019] POST /azenv.php?auth=155070251917&a=PSCN&i=661260957&p=80 => generated 26 bytes in 9 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 97/191] 80.82.70.187 () {32 vars in 421 bytes} [Wed Feb 20 23:45:39 2019] GET /cache/global/img/gs.gif => generated 26 bytes in 9 msecs (HTTP/1.1 400) 1 headers in 53 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 98/192] 47.52.210.94 () {26 vars in 268 bytes} [Thu Feb 21 01:09:33 2019] GET / => generated 26 bytes in 10 msecs (HTTP/1.0 400) 1 headers in 53 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 95/193] 94.231.180.18 () {32 vars in 451 bytes} [Thu Feb 21 01:16:08 2019] GET / => generated 3816 bytes in 5333 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-93:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 96/194] 123.150.183.213 () {48 vars in 979 bytes} [Thu Feb 21 03:04:04 2019] GET / => generated 3819 bytes in 14757 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 97/195] 119.4.249.150 () {38 vars in 675 bytes} [Thu Feb 21 03:04:21 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 98/196] 119.4.249.150 () {40 vars in 845 bytes} [Thu Feb 21 03:04:22 2019] GET / => generated 3816 bytes in 2696 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 99/197] 119.4.249.150 () {38 vars in 675 bytes} [Thu Feb 21 03:04:26 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 100/198] 119.4.249.150 () {42 vars in 876 bytes} [Thu Feb 21 03:04:27 2019] GET / => generated 3816 bytes in 3157 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 101/199] 119.4.249.150 () {42 vars in 888 bytes} [Thu Feb 21 03:04:34 2019] GET /hs/ => generated 124927 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 112 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 99/200] 119.4.249.150 () {46 vars in 965 bytes} [Thu Feb 21 03:04:35 2019] POST /mobileService/query/querySmartBizNew.htm?num=1550718275787 => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
[pid: 7502|app: 0|req: 102/201] 119.4.249.150 () {38 vars in 678 bytes} [Thu Feb 21 03:04:35 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 0)
Exception in thread Thread-97:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 100/202] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 03:14:12 2019] GET / => generated 3819 bytes in 12786 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7501|app: 0|req: 101/203] 119.4.249.150 () {42 vars in 679 bytes} [Thu Feb 21 03:14:29 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 102/204] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 03:14:42 2019] GET / => generated 3816 bytes in 4750 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 103/205] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 03:34:26 2019] GET / => generated 3816 bytes in 6036 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
Exception in thread Thread-92:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 104/206] 119.4.249.150 () {40 vars in 845 bytes} [Thu Feb 21 04:00:00 2019] GET / => generated 3819 bytes in 12748 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
[pid: 7502|app: 0|req: 105/207] 119.4.249.150 () {38 vars in 675 bytes} [Thu Feb 21 04:00:15 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 3)
Exception in thread Thread-101:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 103/208] 119.4.249.150 () {42 vars in 876 bytes} [Thu Feb 21 04:00:16 2019] GET / => generated 3819 bytes in 11583 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
Exception in thread Thread-94:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7502|app: 0|req: 106/209] 119.4.249.150 () {42 vars in 876 bytes} [Thu Feb 21 04:00:29 2019] GET / => generated 3819 bytes in 5176 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 0)
[pid: 7501|app: 0|req: 104/210] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 04:40:56 2019] GET / => generated 3816 bytes in 5636 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 2)
Exception in thread Thread-105:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/python3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'dict' object is not callable

[pid: 7501|app: 0|req: 105/211] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 04:41:15 2019] GET / => generated 3819 bytes in 11375 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 3)
[pid: 7501|app: 0|req: 106/212] 119.4.249.150 () {40 vars in 679 bytes} [Thu Feb 21 04:43:45 2019] GET / => generated 3816 bytes in 2354 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 107/213] 119.4.249.150 () {40 vars in 845 bytes} [Thu Feb 21 04:48:02 2019] GET / => generated 3816 bytes in 6935 msecs (HTTP/1.1 200) 3 headers in 110 bytes (1 switches on core 1)
[pid: 7502|app: 0|req: 108/214] 119.4.249.150 () {38 vars in 675 bytes} [Thu Feb 21 04:48:10 2019] GET /favicon.ico => generated 77 bytes in 1 msecs (HTTP/1.1 404) 3 headers in 100 bytes (1 switches on core 2)
